do setup project
levi-pham-goldenowl/E-Commerce pull request #1
Opened 2022-01-26 08:40 UTC by levi-pham-goldenowl

2022-01-27 11:04 UTC, levi-pham-goldenowl commented
## Task
- Implement Navigation Stack
- Dialog
- Snackbar
- Theme

## Notes/ Blocks
- Packages fluttertoast ver 8.0.8 change background color not working

## Screenshot
![image](https://user-images.githubusercontent.com/97575419/151346744-bf140763-4110-4816-bdad-578efaf4a8a8.png)

2022-01-27 11:14 UTC, levi-pham-goldenowl commented
## Task
- Add font Metropolis

2022-01-27 15:38 UTC, jimmy-to-goldenowl requested changes
Anh có add TODO vào trong code. trước khi push nhớ fix hết các lỗi mà flutter báo nha.
Ngoài ra còn 1 số feedback như.
- Thêm loading screen
- Tích hợp AutoRouter
- Login và Register page sẽ chung 1 Stack
- Tích hợp Flutter bloc. để quán lý trạng thái của app. (isLogin)
- Bổ sung github Action. giống như lần trước a có hướng dẫn. để check code analyze trước khi review

2022-02-07 15:53 UTC, levi-pham-goldenowl commented
Anh hướng dẫn lại giúp em phần github Action với. bữa em quên quay phần đó mất

2022-02-08 03:07 UTC, jimmy-to-goldenowl commented
> Anh hướng dẫn lại giúp em phần github Action với. bữa em quên quay phần đó mất

A tạo rồi nha. Có gì rảnh em search GitHub Action, hay Flutter CI/CD để tìm hiểu thêm nha

2022-02-08 04:14 UTC, jimmy-to-goldenowl commented
Cái này vẫn chưa đạt. em check review của a và làm tiếp nha.

2022-02-08 17:16 UTC, levi-pham-goldenowl commented
thằng action nó báo lỗi anh xem qua giúp em với
![image](https://user-images.githubusercontent.com/97575419/153040056-14940af5-e395-4db0-bd68-ccba072a5375.png)

2022-02-09 02:29 UTC, merged