Products by category screen
levi-pham-goldenowl/E-Commerce pull request #8
Opened 2022-02-28 11:03 UTC by levi-pham-goldenowl

2022-03-02 09:17 UTC, jimmy-to-goldenowl requested changes
See comments?

2022-03-02 09:17 UTC, jimmy-to-goldenowl commented on lib/_dev/firebase_func.dart
>    CollectionReference value =
Please use category_collection_reference instead.

2022-03-02 09:17 UTC, jimmy-to-goldenowl commented on lib/_dev/firebase_func.dart
>      value
Nghiên cứu chổ này. Chỉ gọi 1 API duy nhất. Hiện tại đang dùng vòng lặp và gọi nhiều API

2022-03-02 09:17 UTC, jimmy-to-goldenowl commented on lib/_dev/firebase_func.dart
> +      FirebaseFirestore.instance.collection('Product').withConverter<XProduct>(
Same above: Please use user_collection_reference instead

2022-03-02 09:17 UTC, jimmy-to-goldenowl commented on lib/_dev/firebase_func.dart
> +      FirebaseFirestore.instance.collection('Product').withConverter<XProduct>(
Same above: Please use user_collection_reference instead

2022-03-02 09:17 UTC, jimmy-to-goldenowl commented on lib/_dev/firebase_func.dart
> +    ref.doc(listProduct[i].id).set(listProduct[i], SetOptions(merge: true));
Same above.

2022-03-02 09:17 UTC, jimmy-to-goldenowl commented on lib/src/models/categories_model.dart
> -  int? idCategory;
It should be `String name;`

2022-03-02 09:20 UTC, jimmy-to-goldenowl commented on lib/src/widgets/chip/tag_chip.dart
> +        width: 100,
Width nên để là null. nó phụ thuộc vào label truyền vào

2022-03-03 08:35 UTC, levi-pham-goldenowl commented on lib/src/widgets/chip/tag_chip.dart
> +        width: 100,
chổ này do em thấy design họ set cứng width luôn ấy anh
![image](https://user-images.githubusercontent.com/97575419/156527173-2611f1ef-412c-4dc7-872f-620a424da4b9.png)

2022-03-07 10:34 UTC, jimmy-to-goldenowl approved these changes
See comments. Let merge after finish feedback

2022-03-07 10:34 UTC, jimmy-to-goldenowl commented on lib/src/repositories/features/categories/repo_impl.dart
> +  Future<XResult<List<XCategories>>> addCategory() async {
Chú ý đặt tên đúng với mục đích

2022-03-07 10:34 UTC, jimmy-to-goldenowl commented on lib/src/repositories/features/product/repo_impl.dart
> +      var data = ProductCollectionReference().addProduct();
same above

2022-03-07 10:34 UTC, jimmy-to-goldenowl commented on lib/src/repositories/firestore/collection_ref.dart/categories_collection_reference.dart
> +  Future<XResult<List<XCategories>>> addCategories() async {
same above

2022-03-07 10:34 UTC, jimmy-to-goldenowl commented on lib/src/repositories/firestore/collection_ref.dart/products_collection_reference.dart
> +  Future<XResult<List<XProduct>>> addProduct() async {
same above

2022-03-10 11:23 UTC, merged